global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'VictoriaMetrics'
    static_configs:
      - targets: ['localhost:8428']
    metric_relabel_configs:
      - source_labels: [ __name__ ]
        target_label: "__name__"
        regex: "(.*)"
        action: replace
        replacement: "VM_${1}"
      - source_labels: [ __name__ ]
        target_label: "__name__"
        regex: "VM_vm(.*)"
        action: replace
        replacement: "vm${1}"